USE [master]
GO

/****** Object:  Database [db_sistema_recibos]    Script Date: 14/04/2024 20:29:47 ******/
CREATE DATABASE [db_sistema_recibos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_sistema_recibos', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\db_sistema_recibos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_sistema_recibos_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\db_sistema_recibos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_sistema_recibos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_sistema_recibos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_sistema_recibos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_sistema_recibos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_sistema_recibos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_sistema_recibos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_sistema_recibos] SET  MULTI_USER 
GO

ALTER DATABASE [db_sistema_recibos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_sistema_recibos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_sistema_recibos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_sistema_recibos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_sistema_recibos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_sistema_recibos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [db_sistema_recibos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_sistema_recibos] SET  READ_WRITE 
GO

